apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}

          {{- if .Values.env }}
          env:
{{ .Values.env | toYaml | indent 12 }}
          {{- end }}

          {{- if .Values.ports}}
          ports:
            {{- range $port := .Values.ports }}
            - name: {{ if $port.anubis.enabled }}{{ $port.name }}-plain{{ else }}{{ $port.name }}{{ end }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol | default "TCP" }}
            {{- end }}
          {{- end }}

          {{- if .Values.persistentVolumes }}
          volumeMounts:
            {{- range $volume := .Values.persistentVolumes }}
            - name: {{ list $.Release.Name ($volume | trimPrefix "/" | replace "/" "-") | join "-" }}
              mountPath: {{ $volume }}
            {{- end }}
          {{- end }}

        {{- range $port := .Values.ports }}
        {{- if $port.anubis.enabled }}
        - name: anubis-{{ $port.port }}
          image: {{ $port.anubis.image | default "ghcr.io/techarohq/anubis:latest" | quote }}
          imagePullPolicy: {{ $port.anubis.imagePullPolicy | default "Always" }}
          env:
            - name: "BIND"
              value: ":{{ add $port.port ($port.anubis.portOffset | default 1) }}"
            - name: "DIFFICULTY"
              value: "{{ $port.anubis.difficulty | default 4 }}"
            - name: "METRICS_BIND"
              value: ":{{ $port.anubis.metricsPort | default (add 9090 ($port.anubis.portOffset | default 1)) }}"
            - name: "SERVE_ROBOTS_TXT"
              value: {{ $port.anubis.serveRobotsTxt | default false | toString | quote }}
            - name: "TARGET"
              value: "http://localhost:{{ $port.port }}"
          ports:
            - name: {{ $port.name }}
              containerPort: {{ add $port.port ($port.anubis.portOffset | default 1) }}
              protocol: TCP
            - name: am-{{ $port.anubis.metricsPort | default (add 9090 ($port.anubis.portOffset | default 1)) }}
              containerPort: {{ $port.anubis.metricsPort | default (add 9090 ($port.anubis.portOffset | default 1)) }}
              protocol: TCP
        {{- end }}
        {{- end }}
