apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-sc
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-sc
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-sc
              key: token

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-sapphiccode-net
spec:
  secretName: star-sapphiccode-net-tls
  issuerRef:
    name: cloudflare-sc
    kind: ClusterIssuer
  dnsNames:
    - '*.sapphiccode.net'
