{{ range .Values.minecraft }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-{{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-{{ .name }}
    spec:
      {{ if .serverProperties }}
      initContainers:
        - name: setup-server-properties
          image: registry-1.cc/library/alpine:latest
          command:
            - sh
            - -c
            - |
              echo "{{ .serverProperties | b64enc }}" | base64 -d > /data/server.properties
              chown 1000:1000 /data/server.properties
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      {{ end }}
      containers:
        - name: minecraft
          image: {{ .image | default "ghcr.io/sapphiccode/minecraft:latest-release" | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              name: mc
            - containerPort: 19132
              protocol: UDP
              name: bedrock-udp
            - containerPort: 25575
              name: rcon
          env:
            - name: EULA
              value: "true"
            - name: JAVA_ARGS_EXTRA
              value: {{ .javaArgs | default "-Xmx1G" | quote }}
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-{{ .name }}-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-{{ .name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-{{ .name }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minecraft-{{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: mc
      name: mc
    {{- if .bedrockPort }}
    - protocol: UDP
      port: {{ .bedrockPort }}
      targetPort: bedrock-udp
      name: bedrock-udp
    {{- end }}

{{ end }}
