{{ range .Values.minecraft }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-{{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-{{ .name }}
    spec:
      initContainers:
        {{- if .serverProperties }}
        - name: setup-server-properties
          image: registry-1.cc/library/alpine:latest
          command:
            - sh
            - -c
            - |
              echo "{{ .serverProperties | b64enc }}" | base64 -d > /data/server.properties
              chown 1000:1000 /data/server.properties
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
        {{- end }}
        {{- if .voiceHost }}
        - name: setup-voice-chat
          image: registry-1.cc/library/ubuntu:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /data/config/voicechat
              touch /data/config/voicechat/voicechat-server.properties
              sed -i -e 's/^voice_host=.*/voice_host={{ .voiceHost }}/; t; 1ivoice_host={{ .voiceHost }}' /data/config/voicechat/voicechat-server.properties
              chown 1000:1000 -R /data/config
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
        {{- end }}
      containers:
        - name: minecraft
          image: {{ .image | default "registry-1.cc/itzg/minecraft-server:latest" | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              name: mc
            - containerPort: 19132
              protocol: UDP
              name: bedrock-udp
            - containerPort: 24454
              protocol: UDP
              name: voice
            - containerPort: 25575
              name: rcon
          {{- if .environment }}
          env:
            {{- range $k, $v := .environment }}
            - name: {{ $k | upper | replace "-" "_" | quote}}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-{{ .name }}-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-{{ .name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-{{ .name }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minecraft-{{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: mc
      name: mc
    {{- if .bedrockPort }}
    - protocol: UDP
      port: {{ .bedrockPort }}
      targetPort: bedrock-udp
      name: bedrock-udp
    {{- end }}
    {{- if .voiceHost }}
    - protocol: UDP
      port: {{ .voiceHost | splitList ":" | last | int }}
      targetPort: voice
      name: voice
    {{- end }}

{{ end }}
