apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
{{ (.Files.Glob "config/zot/*").AsConfig | indent 2 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zot
        app.kubernetes.io/version: '{{ .Values.zot.tag }}_{{ (.Files.Glob "config/**/*").AsConfig | sha256sum | trunc 8  }}'
    spec:
      containers:
        - name: zot
          image: '{{ .Values.zot.image }}:{{ .Values.zot.tag }}'
          volumeMounts:
            - name: zot-config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
          args:
            - serve
            - /config/config.yaml
          ports:
            - containerPort: 8080
      volumes:
        - name: zot-config
          configMap:
            name: zot-config
        - name: data
          persistentVolumeClaim:
            claimName: zot-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: zot
spec:
  selector:
    app.kubernetes.io/name: zot
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zot
spec:
  ingressClassName: nginx
  rules:
    - host: zot.blahaj.sapphiccode.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zot
                port:
                  number: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zot
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zot.blahaj.sapphiccode.net`)
      services:
        - name: zot
          port: 80
  tls:
    certResolver: cloudflare
    domains:
      - main: '*.blahaj.sapphiccode.net'
