persistence:
  enabled: true

certificatesResolvers:
  cloudflare:
    acme:
      email: calm.wheel3046@cloak.sapphiccode.net
      dnsChallenge:
        provider: cloudflare
      keyType: EC256
      storage: /data/cloudflare.json

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: token

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
  websecure:
    tls:
      certResolver: cloudflare
      domains:
        - main: "*.blahaj.sapphiccode.net"

providers:
  kubernetesCRD:
    allowEmptyServices: true

logs:
  access:
    enabled: true
    fields:
      defaultMode: keep
      headers:
        defaultMode: drop
        names:
          User-Agent: keep

service:
  spec:
    externalTrafficPolicy: Local
