image: registry-1.cc/library/nginx:latest
imagePullPolicy: IfNotPresent

env:
  - name: "ENV"
    value: "production"
persistentVolumes: []

ports:
  - name: http
    port: 80
    protocol: TCP

    anubis:
      enabled: true
      image: ghcr.io/techarohq/anubis:latest
      imagePullPolicy: Always
      portOffset: 1

service:
  type: ClusterIP

ingressroute:
  enabled: false
