apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-argocd

resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ./ingress-argocd-server.yaml

patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: ./cm-argocd-cmd-params.yaml
