apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-argocd

resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.6/manifests/install.yaml
  - ./ingress-argocd-server.yaml
  - ./ss-openbao-oidc.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: system-argocd
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: add
        path: /rules/-
        value: {"apiGroups": ["*"], "resources": ["pods/exec"], "verbs": ["create"]}
    target:
      kind: ClusterRole
      name: argocd-server
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: ./cm-argocd-cmd-params.yaml
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: ./cm-argocd.yaml
