vault:
  fullnameOverride: vault
  ui:
    enabled: true

postgresql:
  fullnameOverride: postgresql
  primary:
    resourcesPreset: small
    service:
      annotations:
        tailscale.com/expose: "true"

zot:
  image: ghcr.io/project-zot/zot
  tag: v2.1.2

mathesar:
  image: registry-1.cc/mathesar/mathesar
  tag: '0.2.1'

minecraft:
  - name: survival
    port: 25564
    bedrockPort: 19131
    image: registry-1.cc/itzg/minecraft-server:latest
    environment:
      EULA: 'TRUE'
      VERSION: '1.21.5'
      TYPE: QUILT
      MAX_MEMORY: 4G
      REMOVE_OLD_MODS: 'TRUE'
      MODRINTH_PROJECTS: |-
        fabric-api
        lithium
        ferrite-core
        krypton
        c2me-fabric:beta
        no-chat-reports
        distanthorizons:beta
        vmp-fabric:alpha

