vault:
  fullnameOverride: vault
  ui:
    enabled: true

postgresql:
  fullnameOverride: postgresql
  primary:
    resourcesPreset: small
    service:
      annotations:
        tailscale.com/expose: "true"

zot:
  image: ghcr.io/project-zot/zot
  tag: v2.1.2

mathesar:
  image: registry-1.cc/mathesar/mathesar
  tag: '0.2.1'

minecraft:
  - name: survival
    port: 25564
    bedrockPort: 19131
    environment:
      EULA: 'TRUE'
      VERSION: '1.21.5'
      TYPE: QUILT
      MAX_MEMORY: 4G
      MODS: |-
        https://github.com/gnembon/fabric-carpet/releases/download/1.4.169/fabric-carpet-1.21.5-1.4.169+v250325.jar
        https://github.com/gnembon/carpet-extra/releases/download/1.4.169/carpet-extra-1.21.5-1.4.169.jar
      MODRINTH_PROJECTS: |-
        fabric-api
        lithium
        ferrite-core
        krypton
        c2me-fabric:beta
        alternate-current
        vmp-fabric:alpha
        no-chat-reports
        distanthorizons:beta
        carpet-tis-addition
        geyser:beta
        floodgate
        plasmo-voice:beta
        itemswapper

  - name: redstone
    port: 25563
    environment:
      EULA: 'TRUE'
      VERSION: '1.21.5'
      MAX_MEMORY: 4G

      TYPE: QUILT
      MODS: |-
        https://github.com/gnembon/fabric-carpet/releases/download/1.4.169/fabric-carpet-1.21.5-1.4.169+v250325.jar
        https://github.com/gnembon/carpet-extra/releases/download/1.4.169/carpet-extra-1.21.5-1.4.169.jar
      MODRINTH_PROJECTS: |-
        fabric-api
        lithium
        ferrite-core
        alternate-current
        carpet-tis-addition
        worldedit:beta
        plasmo-voice:beta
        itemswapper

      MOTD: "SC's Redstone Server"
      ENABLE_COMMAND_BLOCK: 'true'
      DIFFICULTY: 'hard'
      VIEW_DISTANCE: '16'
      MODE: 'creative'
      LEVEL_TYPE: 'minecraft:flat'
      GENERATE_STRUCTURES: 'false'
      GENERATOR_SETTINGS: '{"biome": "minecraft:plains", "features": false, "lakes": false, "structure_overrides": [], "layers": [{"block": "minecraft:bedrock", "height": 1}, {"block": "minecraft:light_gray_concrete", "height": 112}, {"block": "minecraft:air", "height": 20}, {"block": "minecraft:black_stained_glass", "height": 1}]}'

      RCON_CMDS_STARTUP: |-
        whitelist on
        op SapphicCode
        gamerule doDaylightCycle false
        gamerule doWeatherCycle false
        time set 6000t
