when:
  event:
    - manual
    - cron

steps:
  - name: decrypt
    image: docker.io/library/alpine:latest
    secrets:
      - AGE_ID
    commands:
      - apk add age
      - echo $$AGE_ID > id.age
      - age -i id.age -d restic.env.age > restic.env
      - chmod +x restic.env

  - name: unlock
    when:
      - event: manual
      - event: cron
        cron: daily
      - event: cron
        cron: weekly
    image: docker.io/library/alpine:latest
    volumes:
      - restic_cache:/root/.cache/restic
    commands:
      - apk add restic
      - source restic.env
      - restic unlock

  - name: forget
    when:
      - event: manual
      - event: cron
        cron: weekly
    image: docker.io/library/alpine:latest
    volumes:
      - restic_cache:/root/.cache/restic
    commands:
      - apk add restic
      - source restic.env
      - restic forget --keep-hourly 72 --keep-daily 30 --keep-weekly 52 --keep-monthly unlimited --keep-tag keep

  - name: prune
    when:
      - event: manual
      - event: cron
        cron: weekly
    image: docker.io/library/alpine:latest
    volumes:
      - restic_cache:/root/.cache/restic
    commands:
      - apk add restic
      - source restic.env
      - restic prune

