victoria-metrics-single:
  fullnameOverride: vmetrics
  server:
    scrape:
      enabled: true

victoria-logs-single:
  fullnameOverride: vlogs
  server:
    persistentVolume:
      enabled: true

vector:
  role: Agent
  service:
    enabled: false
  serviceHeadless:
    enabled: false
  customConfig:
    data_dir: /vector-data-dir
    sources:
      kubernetes_logs:
        type: kubernetes_logs
    sinks:
      vlogs:
        type: http
        inputs:
          - kubernetes_logs
        uri: http://vlogs-server:9428/insert/jsonline?_msg_field=message&_stream_fields=kubernetes.pod_namespace,kubernetes.pod_name,kubernetes.container_name&_time_field=timestamp
        compression: gzip
        encoding:
          codec: json
        framing:
          method: newline_delimited
