http:
  address: "0.0.0.0"
  port: 8080

  accessControl:
    repositories:
      "**":
        anonymousPolicy: ["read"]

storage:
  rootDirectory: /data
  retention:
    delay: 24h
    policies:
      - repositories:
          - "**"
        keepTags:
          - patterns:
              - "latest"
              - "stable"
              - "v?\\d+"
              - "v?\\d+\\.\\d+"
            pushedWithin: 24h
          - pulledWithin: 720h

extensions:
  sync:
    registries:
      urls:
        - https://registry-1.docker.io
      onDemand: true
      tlsVerify: true
      content:
        - prefix: "/{library,jenkins}/**"
          tags:
            regex: ".*"
            semver: false
          destination: "/"
          stripPrefix: false
